SPRING_APPLICATION_NAME=task-service
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-task:5432/task_service
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=postgres
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_SHOW_SQL=true
SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000

SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_RETRY_ATTEMPTS=5
SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_RETRY_INTERVAL=5000
SPRINGDOC_API_DOCS_ENABLED=true
SPRINGDOC_SWAGGER_UI_CONFIGURL=/v3/api-docs/swagger-config
SPRINGDOC_SWAGGER_UI_URL=/v3/api-docs
spring.web.resources.static-locations=classpath:/static/,file:/reports/